name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # This example triggers the workflow every day at 5:40 and 5:45 UTC:
    - cron: '40 5 * * *'
    - cron: '45 5 * * *'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build --progress plain -t my-app .

    - name: Run tests
      run: docker run --rm my-app npm run test