version: '3.8'

services:
  express-app:
    profiles:
      - default
    image: express-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - api-testing-network

  newman-app:
    profiles:
      - test
    image: newman-app:latest
    build:
      context: .
      dockerfile: newman.Dockerfile
    entrypoint: [""]
    volumes:
      - ./newman/:/etc/newman
    networks:
      - api-testing-network    
    command: >
      newman run collection.json -e docker.environment.json -k -r htmlextra --reporter-htmlextra-export newman/reports.html

networks:
  api-testing-network:
    driver: bridge
